// Client/my-pwa-app/src/pages/Home.tsx
export default function Home() {
	return (
		<section className="w-full h-full flex flex-col justify-center items-center">
			<h1 className="text-3xl font-black text-nowrap">
				Train <span className="text-primary">Smarter</span> Not Harder
			</h1>
			<p className="text-nowrap">Backed by Science, Driven by data</p>
		</section>
	);
}

// Client/myo-x-app/src/app/home/home.component.ts
import { Component } from "@angular/core";
import { NavigationComponent } from "../shared/navigation/navigation.component";

@Component({
    selector: "home",
    templateUrl: "./home.component.html",
    imports: [NavigationComponent],
})
export class HomeComponent {}

<section class="flex justify-center items-center w-full h-full">
    <div class="flex flex-col items-center">
        <h1 class="text-3xl font-black text-nowrap">
            Train <span class="text-primary">Smart</span> Not Hard
        </h1>
        <h6 class="font-semibold">Backed by science, Driven by data</h6>
    </div>
</section>
