// Client/myo-x-app/src/app/shared/components/navigation/navigation.component.ts
import { NgIf } from "@angular/common";
import { Component, inject, signal } from "@angular/core";
import { RouterLink } from "@angular/router";
import { PWAService } from "../../../core/pwa.service";
import { AuthService } from "../../../core/auth.service";

@Component({
    selector: "navigation",
    templateUrl: "./navigation.component.html",
    imports: [RouterLink, NgIf],
})
export class NavigationComponent {
    private readonly _pwaService = inject(PWAService);
    private readonly _authService = inject(AuthService);

    toggleSideNav = signal(false);

    toggle() {
        this.toggleSideNav.set(!this.toggleSideNav());
    }

    isAvailableForInstall() {
        return this._pwaService.installAvailable();
    }

    installApp() {
        this._pwaService.promptInstall();
    }

    isAuthenticated() {
        return this._authService.isAuthenticated();
    }

    logout() {
        this._authService.logout();
    }
}

<header class="w-full h-14 bg-base-300 flex items-center">
    <div class="fixed z-30 flex justify-between w-full px-5">
        <div class="flex space-x-5">
            <div class="flex items-center lg:hidden">
                <button (click)="toggle()">
                    <svg
                        xmlns="http://www.w3.org/2000/svg"
                        width="24"
                        height="24"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        stroke-width="2"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        class="lucide lucide-align-justify-icon lucide-align-justify"
                    >
                        <path d="M3 12h18" />
                        <path d="M3 18h18" />
                        <path d="M3 6h18" />
                    </svg>
                </button>
            </div>

            <div class="flex items-center lg:hidden">
                <a routerLink="/"
                    ><img
                        class="w-10 h-10 shrink-0"
                        src="/myo-x.svg"
                        alt="myo-x"
                /></a>
            </div>
        </div>

        <div class="flex space-x-7">
            <div *ngIf="isAvailableForInstall()" class="flex items-center">
                <button (click)="installApp()">
                    <svg
                        xmlns="http://www.w3.org/2000/svg"
                        width="24"
                        height="24"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        stroke-width="2"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        class="lucide lucide-download-icon lucide-download"
                    >
                        <path d="M21 15v4a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2v-4" />
                        <polyline points="7 10 12 15 17 10" />
                        <line x1="12" x2="12" y1="15" y2="3" />
                    </svg>
                </button>
            </div>

            <div class="flex items-center">
                @if(isAuthenticated()) {
                <span (click)="logout()" class="font-bold"
                    ><a routerLink="/">Logout</a></span
                >
                } @else {
                <span class="font-bold"
                    ><a routerLink="/auth/login">Login</a></span
                >
                }
            </div>
        </div>
    </div>

    <nav
        class="fixed z-50 top-0 bg-base-200 w-1/2 h-screen px-6 py-3 space-y-10 transition-all duration-300 {{
            toggleSideNav() ? 'left-0' : '-left-full'
        }} lg:left-0 lg:w-[35%]"
    >
        <div class="flex flex-wrap justify-between items-center">
            <div class="flex items-center space-x-3">
                <img class="w-12 h-12" src="/myo-x.svg" alt="myo-x" />
                <h1 class="text-2xl font-black text-nowrap">Myo X</h1>
            </div>

            <div class="lg:hidden">
                <button (click)="toggle()">
                    <svg
                        xmlns="http://www.w3.org/2000/svg"
                        width="24"
                        height="24"
                        viewBox="0 0 24 24"
                        fill="none"
                        stroke="currentColor"
                        stroke-width="2"
                        stroke-linecap="round"
                        stroke-linejoin="round"
                        class="lucide lucide-x-icon lucide-x"
                    >
                        <path d="M18 6 6 18" />
                        <path d="m6 6 12 12" />
                    </svg>
                </button>
            </div>
        </div>

        <div>
            <ul class="space-y-3 font-bold">
                <li><a routerLink="/dashboard">Dashboard</a></li>
                <li>Workout</li>
            </ul>
        </div>
    </nav>

    @if (toggleSideNav()) {
    <div (click)="toggle()" class="fixed z-40 w-full h-screen top-0"></div>
    }
</header>

// Client/my-pwa-app/src/shared/components/Navigation.tsx
import { useState } from "react";
import { Link } from "react-router";
import { logoutUser } from "../../services/AuthService";
import { clearUserAccessToken } from "../../utils/offlineAuth";
import useAuth from "../../hooks/useAuth";

export default function Navigation() {
	const [showMenu, setShowMenu] = useState(false);
	const { isAuthenticated, setIsAuthenticated } = useAuth();

	function handleClick() {
		setShowMenu(!showMenu);
	}

	function handleLogoutClick() {
		if (isAuthenticated) {
			logoutUser();
			setIsAuthenticated(false);
			clearUserAccessToken();
		}
	}

	return (
		<>
			<div
				className={`fixed left-0 top-0 z-20 bg-base-300 font-primary h-full w-4/5 space-y-10 px-3 py-2 ${
					showMenu ? "translate-x-0" : "-translate-x-full"
				} duration-300 transition-transform sm:w-1/2`}
			>
				<div className="flex justify-between">
					<div>
						<Link to="/">
							<div className="flex items-center space-x-2">
								<img
									className="w-10 h-10"
									src="/myo-x.svg"
									alt="myo-x"
								/>
								<h1 className="font-bold text-nowrap text-xl">
									Myo X
								</h1>
							</div>
						</Link>
					</div>

					<div className="flex-none">
						<button
							onClick={handleClick}
							className="btn btn-square btn-ghost"
						>
							<svg
								xmlns="http://www.w3.org/2000/svg"
								fill="none"
								viewBox="0 0 24 24"
								strokeWidth={1.5}
								stroke="currentColor"
								className="size-6"
							>
								<path
									strokeLinecap="round"
									strokeLinejoin="round"
									d="M6 18 18 6M6 6l12 12"
								/>
							</svg>
						</button>
					</div>
				</div>

				<nav>
					<ul className="space-y-3">
						<li>
							<Link to="/dashboard">Dashboard</Link>
						</li>

						<li>
							<Link to="/workouts">Workouts</Link>
						</li>
					</ul>
				</nav>
			</div>

			<header className="flex justify-between p-4 bg-base-300">
				<div className="flex">
					{isAuthenticated && (
						<div className="flex-none">
							<button
								onClick={handleClick}
								className="btn btn-square btn-ghost"
							>
								<svg
									xmlns="http://www.w3.org/2000/svg"
									fill="none"
									viewBox="0 0 24 24"
									className="inline-block h-5 w-5 stroke-current"
								>
									{" "}
									<path
										strokeLinecap="round"
										strokeLinejoin="round"
										strokeWidth="2"
										d="M4 6h16M4 12h16M4 18h16"
									></path>{" "}
								</svg>
							</button>
						</div>
					)}

					<Link to="/">
						<div className="flex items-center space-x-2">
							<img
								className="w-10 h-10"
								src="/myo-x.svg"
								alt="myo-x"
							/>
							<h1 className="font-bold text-xl text-nowrap">
								Myo X
							</h1>
						</div>
					</Link>
				</div>

				<div className="flex items-center">
					<Link
						onClick={handleLogoutClick}
						to={isAuthenticated ? "/" : "/auth/login"}
					>
						{isAuthenticated ? "Logout" : "Login"}
					</Link>
				</div>
			</header>

			{showMenu && (
				<div
					onClick={() => setShowMenu(false)}
					className="fixed w-full h-full z-10"
				></div>
			)}
		</>
	);
}
